### ISSUE TITLE
[dolphin]: does not "autorefresh" when new content is added to current open folder

### ISSUE THREAD

**Issue by star-buck** [blue-systems/maui-netrunner-issues#42]
example is extracting something with ark, etc.

**Comment by davidedmundson** [comment]
Is this Maui or Netrunner?

**Comment by llelectronics** [comment]
Just as info. libfam0 is installed (which should take care of it)

**Comment by star-buck** [comment]
its really weird, sometimes i have to press F5 to see files, sometimes its instantly updated.
Seen on Maui-1 based on neon.

**Comment by star-buck** [comment]
will test for sure later and try to reproduce circumstances with awaited Maui-1 ISO (currently testing netrunner core on that hardware).
