### ISSUE TITLE
[netrunner and maui]: add package "desktop-file-utils"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/maui-netrunner-issues#43]

**Comment by llelectronics** [comment]
Maui 1 has it installed: 

> desktop-file-utils:
>   Installed: 0.22-1ubuntu5
>   Candidate: 0.22-1ubuntu5
>   Version table:
>  *** 0.22-1ubuntu5 500
>         500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by shadeslayer** [comment]
Added for NC, will be in the next image
